### ISSUE TITLE
a bit of extraneous code?

### ISSUE THREAD

**Issue by heckj** [The-Igor/d3-color#1]
hi @The-Igor - saw this flow by on Swift Package Index and glanced into the code. 

Reading through it, it looks like you might have a copy/paste error with some code that wouldn't normally be reached lurking about in there at https://github.com/The-Igor/d3-color/blob/main/Sources/d3-color/Color%2BExt.swift#L39-L41

**Comment by The-Igor** [comment]
Hi @heckj 
Thank you for the remark. I thought my repo is one of the million that nobody reads:) I know you. You are my teacher of Combine! You were the first source. Thank you for your work on this! I quite grateful that you found the time to take a look on my profile!
